**Bugs**
I had this error in the process of developing File "/workspace/.pip-modules/lib/python3.8/site-packages/dj_database_url.py", line 80, in parse